version: '3.4'

services:
  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./srs/Services/Catalog/Catalog.API
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
